### PR TITLE
adding integration with polars

### PR DESCRIPTION
**Pull request by benjaminjellis**
Hi, 

First off I've been playing around with the crate and I think it's really great.

One thing that I thought might be useful is to have integration with [polars](https://github.com/pola-rs/polars) (i.e. something like pandas integration with sklearn in python)

I've added a new constructor method ```from_dataframe``` for the ```Dataset``` struct and packaged it under a new crate feature ```dataframe``` 

I'm not sure if you're accepting contributions and whether a contribution like this would be something you'd want. Feel free to close the pr if not. 

Let me know what you think!

Thanks :)

### CODE REVIEW

**Review by vaaaaanquish — APPROVED** [review]
LGTM

**Comment by loxs** [comment]
Hi, I'm getting this error
```
expected struct `polars_core::frame::DataFrame`, found struct `polars::prelude::DataFrame`
```

@benjaminjellis how are you using polars, are you using it from polars_core crate?

**Comment by benjaminjellis** [comment]
Hi @loxs,

The usage that's tested is using something like 
```rust
use polars::df;
```

An example of this is [here](https://github.com/vaaaaanquish/lightgbm-rs/blob/fdac51534170d6ff23d2628827d0d620128f4c1f/src/dataset.rs#L228-L242)

i.e. this crate uses polars not polars_core. 

Hopefully that helps! Any more questions lmk!

Thanks :)

**Comment by loxs** [comment]
Hm, it seems that it's because of polars version mismatch. I am using v 0.20 in the other parts of my software and this crate dpeneds on 0.16... seems like they did some reorg and types are no more compatible.

Thanks!

**Pull request merged**
