### PR TITLE
Add linter CI and refactoring

### PR DESCRIPTION
**Pull request by paq**
- Add CI to run clippy and format checking.
- Fixes all clippy warning.
  - Removes unused imports.
  - Removes primitive casting.
  - Removes unnecessary wrapping results and `?`.
- Format examples.
- Shorten some `if` expressions.
- Uses `new` to construct LGBMError.

### CODE REVIEW

**Comment by paq** [comment]
Umm, maybe not allowed creating new action from fork repos.

**Comment by vaaaaanquish** [comment]
@paq I see. Shall we merge them once? The code is LGTM.
```
Warning: It seems that this Action is executed from the forked repository.
Warning: GitHub Actions are not allowed to create Check annotations, when executed for a forked repos. See https://github.com/actions-rs/clippy-check/issues/2 for details.
```

**Comment by paq** [comment]
@vaaaaanquish Yes, let's. Thanks.

**Comment by paq** [comment]
Thanks for merging.

Clippy now works but failed.
It looks like we need to avoid building lightgbm on lint.

**Pull request merged**
